/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misc;

import classifier.LinearClassifier;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.Random;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author dee
 */
public class Ai1DGui extends javax.swing.JFrame {

    /**
     * Creates new form Ai1DGui
     */
    final VisualComponents comp;
    HashMap<String, Component> cp;
    public double[][] data;
    public double[][] labels;
    int ss = 200;
    int height = 400;
    int width = 400;
    private LinearClassifier model;

    public Ai1DGui() {
        initComponents();
        model = new LinearClassifier();

        comp = new VisualComponents();
        comp.setBorder(new EtchedBorder(2));
        comp.setPreferredSize(new Dimension(height, width));
        getContentPane().add(comp, BorderLayout.CENTER);
        comp.clearLines();
        comp.clearDots();
        regen_data(20);
        drawData();
        pack();
    }

    public void drawData() {
//        for (int i = 0; i < data.length; i++) {
//            comp.addDot(
//                    data[i][0] * ss + width,
//                    labels[i][0] * ss + height,
//                    Color.BLUE
//            );
//        }
//        for (int i = 0; i < model.getNumData(); i++) {
////            System.out.println(model.getData(i, 0) + "-" + model.getData(i, 1));
//            comp.addDot(
//                    model.getData(i, 0) * model.getSs() + model.getWidth() / 2,
//                    model.getData(i, 1) * model.getSs() + model.getHeight() / 2,
//                    model.getDataColor(model.getLabels(i)));
//        }
    }

    public void regen_data(int N) {
        Random r = new Random();
        data = new double[N][1];
        labels = new double[N][1];
        for (int i = 0; i < N; i++) {
            double x = r.nextDouble() * 10 - 5;
            data[i][0] = x;
            labels[i][0] = x * Math.sin(x);
        }
        for (int i = 0; i < data.length; i++) {
            System.out.println(data[i][0] + " " + labels[i][0]);

        }
    }

    public void init() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ai1DGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ai1DGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ai1DGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ai1DGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new Ai1DGui().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
